language: android
before_script:
        - chmod +x gradlewy
android:
        components:
                - build-tools-3.2.1
                - android-27
                - extra-google-google_play_services
                - extra-google-m2repository
                - extra-android-m2repository
                - addon-google_apis-google-26
                - sys-img-armeabi-v7a-android-27
